version: '3.8'

services:
  cibi-api:
    image: ufleck/cibi:latest
    build: .
    ports:
      - "42069:42069"
    volumes:
      - ./data:/data
    environment:
      CIBI_DATABASEPATH: /data/cibi.db
      CIBI_SERVERPORT: :42069
      CIBI_SAFETYBUFFER: 1000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:42069/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
